FUNCTION-POOL ZFSCM_DM.                     "MESSAGE-ID ..

* INCLUDE LZFSCM_DMD...                      " Local class definition

DATA Gt_SCMGATTR_REASONT type SCMGATTR_REASONT OCCURS 1 WITH HEADER LINE.
DATA Gt_ZFSCM_DM_ACTT type ZFSCM_DM_ACTT OCCURS 1 WITH HEADER LINE.
