*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 28.08.2019 at 16:39:54
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_CAT_REA................................*
FORM GET_DATA_ZVFIFSCM_CAT_REA.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIFSCM_CAT_REAS WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_CAT_REA .
ZVFIFSCM_CAT_REA-MANDT =
ZFIFSCM_CAT_REAS-MANDT .
ZVFIFSCM_CAT_REA-CASE_TYPE =
ZFIFSCM_CAT_REAS-CASE_TYPE .
ZVFIFSCM_CAT_REA-CATEGORY =
ZFIFSCM_CAT_REAS-CATEGORY .
ZVFIFSCM_CAT_REA-REASON_CODE =
ZFIFSCM_CAT_REAS-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
CATEGORY = ZFIFSCM_CAT_REAS-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
REASON_CODE = ZFIFSCM_CAT_REAS-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-REASON_DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_CAT_REA.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_CAT_REA .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_CAT_REA.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_CAT_REA-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_CAT_REAS WHERE
  CASE_TYPE = ZVFIFSCM_CAT_REA-CASE_TYPE AND
  CATEGORY = ZVFIFSCM_CAT_REA-CATEGORY AND
  REASON_CODE = ZVFIFSCM_CAT_REA-REASON_CODE .
    IF SY-SUBRC = 0.
    DELETE ZFIFSCM_CAT_REAS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_CAT_REAS WHERE
  CASE_TYPE = ZVFIFSCM_CAT_REA-CASE_TYPE AND
  CATEGORY = ZVFIFSCM_CAT_REA-CATEGORY AND
  REASON_CODE = ZVFIFSCM_CAT_REA-REASON_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIFSCM_CAT_REAS.
    ENDIF.
ZFIFSCM_CAT_REAS-MANDT =
ZVFIFSCM_CAT_REA-MANDT .
ZFIFSCM_CAT_REAS-CASE_TYPE =
ZVFIFSCM_CAT_REA-CASE_TYPE .
ZFIFSCM_CAT_REAS-CATEGORY =
ZVFIFSCM_CAT_REA-CATEGORY .
ZFIFSCM_CAT_REAS-REASON_CODE =
ZVFIFSCM_CAT_REA-REASON_CODE .
    IF SY-SUBRC = 0.
    UPDATE ZFIFSCM_CAT_REAS ##WARN_OK.
    ELSE.
    INSERT ZFIFSCM_CAT_REAS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_CAT_REA-UPD_FLAG,
STATUS_ZVFIFSCM_CAT_REA-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_CAT_REA.
  SELECT SINGLE * FROM ZFIFSCM_CAT_REAS WHERE
CASE_TYPE = ZVFIFSCM_CAT_REA-CASE_TYPE AND
CATEGORY = ZVFIFSCM_CAT_REA-CATEGORY AND
REASON_CODE = ZVFIFSCM_CAT_REA-REASON_CODE .
ZVFIFSCM_CAT_REA-MANDT =
ZFIFSCM_CAT_REAS-MANDT .
ZVFIFSCM_CAT_REA-CASE_TYPE =
ZFIFSCM_CAT_REAS-CASE_TYPE .
ZVFIFSCM_CAT_REA-CATEGORY =
ZFIFSCM_CAT_REAS-CATEGORY .
ZVFIFSCM_CAT_REA-REASON_CODE =
ZFIFSCM_CAT_REAS-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
CATEGORY = ZFIFSCM_CAT_REAS-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_CAT_REA-CAT_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_CAT_REA-CAT_DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
REASON_CODE = ZFIFSCM_CAT_REAS-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-REASON_DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_CAT_REA-REASON_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_CAT_REA-REASON_DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_CAT_REA USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_CAT_REA-CASE_TYPE TO
ZFIFSCM_CAT_REAS-CASE_TYPE .
MOVE ZVFIFSCM_CAT_REA-CATEGORY TO
ZFIFSCM_CAT_REAS-CATEGORY .
MOVE ZVFIFSCM_CAT_REA-REASON_CODE TO
ZFIFSCM_CAT_REAS-REASON_CODE .
MOVE ZVFIFSCM_CAT_REA-MANDT TO
ZFIFSCM_CAT_REAS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIFSCM_CAT_REAS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIFSCM_CAT_REAS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIFSCM_CAT_REAS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFIFSCM_CAT_REA USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFIFSCM_CAT_REAS-MANDT =
ZVFIFSCM_CAT_REA-MANDT .
ZFIFSCM_CAT_REAS-CASE_TYPE =
ZVFIFSCM_CAT_REA-CASE_TYPE .
ZFIFSCM_CAT_REAS-CATEGORY =
ZVFIFSCM_CAT_REA-CATEGORY .
ZFIFSCM_CAT_REAS-REASON_CODE =
ZVFIFSCM_CAT_REA-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
CATEGORY = ZFIFSCM_CAT_REAS-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_CAT_REA-CAT_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_CAT_REA-CAT_DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_CAT_REAS-CASE_TYPE AND
REASON_CODE = ZFIFSCM_CAT_REAS-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_CAT_REA-REASON_DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_CAT_REA-REASON_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_CAT_REA-REASON_DESCRIPTION .
    ENDIF.
ENDFORM.
