*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 05.08.2019 at 16:26:43
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_REASON.................................*
FORM GET_DATA_ZVFIFSCM_REASON.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SCMGATTR_REASON WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_REASON .
ZVFIFSCM_REASON-MANDT =
SCMGATTR_REASON-MANDT .
ZVFIFSCM_REASON-CASE_TYPE =
SCMGATTR_REASON-CASE_TYPE .
ZVFIFSCM_REASON-REASON_CODE =
SCMGATTR_REASON-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_REASON-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_REASON.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_REASON .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_REASON.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_REASON-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SCMGATTR_REASON WHERE
  CASE_TYPE = ZVFIFSCM_REASON-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_REASON-REASON_CODE .
    IF SY-SUBRC = 0.
    DELETE SCMGATTR_REASON .
    ENDIF.
    DELETE FROM SCMGATTR_REASONT WHERE
    CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
    REASON_CODE = SCMGATTR_REASON-REASON_CODE .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SCMGATTR_REASON WHERE
  CASE_TYPE = ZVFIFSCM_REASON-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_REASON-REASON_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SCMGATTR_REASON.
    ENDIF.
SCMGATTR_REASON-MANDT =
ZVFIFSCM_REASON-MANDT .
SCMGATTR_REASON-CASE_TYPE =
ZVFIFSCM_REASON-CASE_TYPE .
SCMGATTR_REASON-REASON_CODE =
ZVFIFSCM_REASON-REASON_CODE .
    IF SY-SUBRC = 0.
    UPDATE SCMGATTR_REASON ##WARN_OK.
    ELSE.
    INSERT SCMGATTR_REASON .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM SCMGATTR_REASONT WHERE
    CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
    REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR SCMGATTR_REASONT.
SCMGATTR_REASONT-CASE_TYPE =
SCMGATTR_REASON-CASE_TYPE .
SCMGATTR_REASONT-REASON_CODE =
SCMGATTR_REASON-REASON_CODE .
SCMGATTR_REASONT-LANGU =
SY-LANGU .
      ENDIF.
SCMGATTR_REASONT-DESCRIPTION =
ZVFIFSCM_REASON-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE SCMGATTR_REASONT ##WARN_OK.
    ELSE.
    INSERT SCMGATTR_REASONT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_REASON-UPD_FLAG,
STATUS_ZVFIFSCM_REASON-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_REASON.
  SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZVFIFSCM_REASON-CASE_TYPE AND
REASON_CODE = ZVFIFSCM_REASON-REASON_CODE .
ZVFIFSCM_REASON-MANDT =
SCMGATTR_REASON-MANDT .
ZVFIFSCM_REASON-CASE_TYPE =
SCMGATTR_REASON-CASE_TYPE .
ZVFIFSCM_REASON-REASON_CODE =
SCMGATTR_REASON-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_REASON-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_REASON-DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_REASON USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_REASON-CASE_TYPE TO
SCMGATTR_REASON-CASE_TYPE .
MOVE ZVFIFSCM_REASON-REASON_CODE TO
SCMGATTR_REASON-REASON_CODE .
MOVE ZVFIFSCM_REASON-MANDT TO
SCMGATTR_REASON-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SCMGATTR_REASON'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SCMGATTR_REASON TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SCMGATTR_REASON'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE SCMGATTR_REASON-CASE_TYPE TO
SCMGATTR_REASONT-CASE_TYPE .
MOVE SCMGATTR_REASON-REASON_CODE TO
SCMGATTR_REASONT-REASON_CODE .
MOVE SY-LANGU TO
SCMGATTR_REASONT-LANGU .
MOVE ZVFIFSCM_REASON-MANDT TO
SCMGATTR_REASONT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SCMGATTR_REASONT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SCMGATTR_REASONT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SCMGATTR_REASONT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
