*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 28.08.2019 at 17:36:02
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_ACTION.................................*
FORM GET_DATA_ZVFIFSCM_ACTION.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIFSCM_ACTION WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_ACTION .
ZVFIFSCM_ACTION-MANDT =
ZFIFSCM_ACTION-MANDT .
ZVFIFSCM_ACTION-CASE_TYPE =
ZFIFSCM_ACTION-CASE_TYPE .
ZVFIFSCM_ACTION-ACTION_ID =
ZFIFSCM_ACTION-ACTION_ID .
    SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_ACTION-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_ACTION.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_ACTION .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_ACTION.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_ACTION-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_ACTION WHERE
  CASE_TYPE = ZVFIFSCM_ACTION-CASE_TYPE AND
  ACTION_ID = ZVFIFSCM_ACTION-ACTION_ID .
    IF SY-SUBRC = 0.
    DELETE ZFIFSCM_ACTION .
    ENDIF.
    DELETE FROM ZFIFSCM_ACTIONT WHERE
    CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
    ACTION_ID = ZFIFSCM_ACTION-ACTION_ID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_ACTION WHERE
  CASE_TYPE = ZVFIFSCM_ACTION-CASE_TYPE AND
  ACTION_ID = ZVFIFSCM_ACTION-ACTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIFSCM_ACTION.
    ENDIF.
ZFIFSCM_ACTION-MANDT =
ZVFIFSCM_ACTION-MANDT .
ZFIFSCM_ACTION-CASE_TYPE =
ZVFIFSCM_ACTION-CASE_TYPE .
ZFIFSCM_ACTION-ACTION_ID =
ZVFIFSCM_ACTION-ACTION_ID .
    IF SY-SUBRC = 0.
    UPDATE ZFIFSCM_ACTION ##WARN_OK.
    ELSE.
    INSERT ZFIFSCM_ACTION .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_ACTIONT WHERE
    CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
    ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZFIFSCM_ACTIONT.
ZFIFSCM_ACTIONT-CASE_TYPE =
ZFIFSCM_ACTION-CASE_TYPE .
ZFIFSCM_ACTIONT-ACTION_ID =
ZFIFSCM_ACTION-ACTION_ID .
ZFIFSCM_ACTIONT-LANGU =
SY-LANGU .
      ENDIF.
ZFIFSCM_ACTIONT-ACTION_TEXT =
ZVFIFSCM_ACTION-ACTION_TEXT .
    IF SY-SUBRC = 0.
    UPDATE ZFIFSCM_ACTIONT ##WARN_OK.
    ELSE.
    INSERT ZFIFSCM_ACTIONT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_ACTION-UPD_FLAG,
STATUS_ZVFIFSCM_ACTION-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_ACTION.
  SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
CASE_TYPE = ZVFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZVFIFSCM_ACTION-ACTION_ID .
ZVFIFSCM_ACTION-MANDT =
ZFIFSCM_ACTION-MANDT .
ZVFIFSCM_ACTION-CASE_TYPE =
ZFIFSCM_ACTION-CASE_TYPE .
ZVFIFSCM_ACTION-ACTION_ID =
ZFIFSCM_ACTION-ACTION_ID .
    SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_ACTION-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_ACTION-ACTION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_ACTION USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_ACTION-CASE_TYPE TO
ZFIFSCM_ACTION-CASE_TYPE .
MOVE ZVFIFSCM_ACTION-ACTION_ID TO
ZFIFSCM_ACTION-ACTION_ID .
MOVE ZVFIFSCM_ACTION-MANDT TO
ZFIFSCM_ACTION-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIFSCM_ACTION'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIFSCM_ACTION TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIFSCM_ACTION'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZFIFSCM_ACTION-CASE_TYPE TO
ZFIFSCM_ACTIONT-CASE_TYPE .
MOVE ZFIFSCM_ACTION-ACTION_ID TO
ZFIFSCM_ACTIONT-ACTION_ID .
MOVE SY-LANGU TO
ZFIFSCM_ACTIONT-LANGU .
MOVE ZVFIFSCM_ACTION-MANDT TO
ZFIFSCM_ACTIONT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIFSCM_ACTIONT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIFSCM_ACTIONT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIFSCM_ACTIONT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
