*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 05.08.2019 at 16:32:05
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_CASE...................................*
FORM GET_DATA_ZVFIFSCM_CASE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SCMGCASETYPE WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_CASE .
ZVFIFSCM_CASE-CLIENT =
SCMGCASETYPE-CLIENT .
ZVFIFSCM_CASE-CASE_TYPE =
SCMGCASETYPE-CASE_TYPE .
    SELECT SINGLE * FROM SCMGCASETYPET WHERE
CASE_TYPE = SCMGCASETYPE-CASE_TYPE AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_CASE-DESCRIPTION =
SCMGCASETYPET-DESCRIPTION .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_CASE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_CASE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_CASE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_CASE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SCMGCASETYPE WHERE
  CASE_TYPE = ZVFIFSCM_CASE-CASE_TYPE .
    IF SY-SUBRC = 0.
    DELETE SCMGCASETYPE .
    ENDIF.
    DELETE FROM SCMGCASETYPET WHERE
    CASE_TYPE = SCMGCASETYPE-CASE_TYPE .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SCMGCASETYPE WHERE
  CASE_TYPE = ZVFIFSCM_CASE-CASE_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SCMGCASETYPE.
    ENDIF.
SCMGCASETYPE-CLIENT =
ZVFIFSCM_CASE-CLIENT .
SCMGCASETYPE-CASE_TYPE =
ZVFIFSCM_CASE-CASE_TYPE .
    IF SY-SUBRC = 0.
    UPDATE SCMGCASETYPE ##WARN_OK.
    ELSE.
    INSERT SCMGCASETYPE .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM SCMGCASETYPET WHERE
    CASE_TYPE = SCMGCASETYPE-CASE_TYPE AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR SCMGCASETYPET.
SCMGCASETYPET-CASE_TYPE =
SCMGCASETYPE-CASE_TYPE .
SCMGCASETYPET-LANGU =
SY-LANGU .
      ENDIF.
SCMGCASETYPET-DESCRIPTION =
ZVFIFSCM_CASE-DESCRIPTION .
    IF SY-SUBRC = 0.
    UPDATE SCMGCASETYPET ##WARN_OK.
    ELSE.
    INSERT SCMGCASETYPET .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_CASE-UPD_FLAG,
STATUS_ZVFIFSCM_CASE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_CASE.
  SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZVFIFSCM_CASE-CASE_TYPE .
ZVFIFSCM_CASE-CLIENT =
SCMGCASETYPE-CLIENT .
ZVFIFSCM_CASE-CASE_TYPE =
SCMGCASETYPE-CASE_TYPE .
    SELECT SINGLE * FROM SCMGCASETYPET WHERE
CASE_TYPE = SCMGCASETYPE-CASE_TYPE AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFIFSCM_CASE-DESCRIPTION =
SCMGCASETYPET-DESCRIPTION .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_CASE-DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_CASE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_CASE-CASE_TYPE TO
SCMGCASETYPE-CASE_TYPE .
MOVE ZVFIFSCM_CASE-CLIENT TO
SCMGCASETYPE-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SCMGCASETYPE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SCMGCASETYPE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SCMGCASETYPE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE SCMGCASETYPE-CASE_TYPE TO
SCMGCASETYPET-CASE_TYPE .
MOVE SY-LANGU TO
SCMGCASETYPET-LANGU .
MOVE ZVFIFSCM_CASE-CLIENT TO
SCMGCASETYPET-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SCMGCASETYPET'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SCMGCASETYPET TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SCMGCASETYPET'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
