*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 07.08.2019 at 14:18:28
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_ASSIGN.................................*
FORM GET_DATA_ZVFIFSCM_ASSIGN.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIFSCM_ASSIGN WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_ASSIGN .
ZVFIFSCM_ASSIGN-MANDT =
ZFIFSCM_ASSIGN-MANDT .
ZVFIFSCM_ASSIGN-CASE_TYPE =
ZFIFSCM_ASSIGN-CASE_TYPE .
ZVFIFSCM_ASSIGN-REASON_CODE =
ZFIFSCM_ASSIGN-REASON_CODE .
ZVFIFSCM_ASSIGN-ACTION_ID =
ZFIFSCM_ASSIGN-ACTION_ID .
ZVFIFSCM_ASSIGN-ACTIVE =
ZFIFSCM_ASSIGN-ACTIVE .
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
ACTION_ID = ZFIFSCM_ASSIGN-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_ASSIGN-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_ASSIGN.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_ASSIGN .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_ASSIGN.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_ASSIGN-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_ASSIGN WHERE
  CASE_TYPE = ZVFIFSCM_ASSIGN-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_ASSIGN-REASON_CODE AND
  ACTION_ID = ZVFIFSCM_ASSIGN-ACTION_ID .
    IF SY-SUBRC = 0.
    DELETE ZFIFSCM_ASSIGN .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_ASSIGN WHERE
  CASE_TYPE = ZVFIFSCM_ASSIGN-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_ASSIGN-REASON_CODE AND
  ACTION_ID = ZVFIFSCM_ASSIGN-ACTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIFSCM_ASSIGN.
    ENDIF.
ZFIFSCM_ASSIGN-MANDT =
ZVFIFSCM_ASSIGN-MANDT .
ZFIFSCM_ASSIGN-CASE_TYPE =
ZVFIFSCM_ASSIGN-CASE_TYPE .
ZFIFSCM_ASSIGN-REASON_CODE =
ZVFIFSCM_ASSIGN-REASON_CODE .
ZFIFSCM_ASSIGN-ACTION_ID =
ZVFIFSCM_ASSIGN-ACTION_ID .
ZFIFSCM_ASSIGN-ACTIVE =
ZVFIFSCM_ASSIGN-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZFIFSCM_ASSIGN ##WARN_OK.
    ELSE.
    INSERT ZFIFSCM_ASSIGN .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_ASSIGN-UPD_FLAG,
STATUS_ZVFIFSCM_ASSIGN-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_ASSIGN.
  SELECT SINGLE * FROM ZFIFSCM_ASSIGN WHERE
CASE_TYPE = ZVFIFSCM_ASSIGN-CASE_TYPE AND
REASON_CODE = ZVFIFSCM_ASSIGN-REASON_CODE AND
ACTION_ID = ZVFIFSCM_ASSIGN-ACTION_ID .
ZVFIFSCM_ASSIGN-MANDT =
ZFIFSCM_ASSIGN-MANDT .
ZVFIFSCM_ASSIGN-CASE_TYPE =
ZFIFSCM_ASSIGN-CASE_TYPE .
ZVFIFSCM_ASSIGN-REASON_CODE =
ZFIFSCM_ASSIGN-REASON_CODE .
ZVFIFSCM_ASSIGN-ACTION_ID =
ZFIFSCM_ASSIGN-ACTION_ID .
ZVFIFSCM_ASSIGN-ACTIVE =
ZFIFSCM_ASSIGN-ACTIVE .
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
ACTION_ID = ZFIFSCM_ASSIGN-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_ASSIGN-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_ASSIGN-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_ASSIGN-ACTION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_ASSIGN USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_ASSIGN-CASE_TYPE TO
ZFIFSCM_ASSIGN-CASE_TYPE .
MOVE ZVFIFSCM_ASSIGN-REASON_CODE TO
ZFIFSCM_ASSIGN-REASON_CODE .
MOVE ZVFIFSCM_ASSIGN-ACTION_ID TO
ZFIFSCM_ASSIGN-ACTION_ID .
MOVE ZVFIFSCM_ASSIGN-MANDT TO
ZFIFSCM_ASSIGN-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIFSCM_ASSIGN'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIFSCM_ASSIGN TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIFSCM_ASSIGN'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFIFSCM_ASSIGN USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFIFSCM_ASSIGN-MANDT =
ZVFIFSCM_ASSIGN-MANDT .
ZFIFSCM_ASSIGN-CASE_TYPE =
ZVFIFSCM_ASSIGN-CASE_TYPE .
ZFIFSCM_ASSIGN-REASON_CODE =
ZVFIFSCM_ASSIGN-REASON_CODE .
ZFIFSCM_ASSIGN-ACTION_ID =
ZVFIFSCM_ASSIGN-ACTION_ID .
ZFIFSCM_ASSIGN-ACTIVE =
ZVFIFSCM_ASSIGN-ACTIVE .
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
ACTION_ID = ZFIFSCM_ASSIGN-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_ASSIGN-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_ASSIGN-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_ASSIGN-ACTION_TEXT .
    ENDIF.
ENDFORM.
