*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 30.08.2019 at 14:23:18
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFIFSCM_REAS_AC................................*
FORM GET_DATA_ZVFIFSCM_REAS_AC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFIFSCM_REAS_ACT WHERE
(VIM_WHERETAB) .
    CLEAR ZVFIFSCM_REAS_AC .
ZVFIFSCM_REAS_AC-MANDT =
ZFIFSCM_REAS_ACT-MANDT .
ZVFIFSCM_REAS_AC-CASE_TYPE =
ZFIFSCM_REAS_ACT-CASE_TYPE .
ZVFIFSCM_REAS_AC-REASON_CODE =
ZFIFSCM_REAS_ACT-REASON_CODE .
ZVFIFSCM_REAS_AC-ACTION_ID =
ZFIFSCM_REAS_ACT-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
REASON_CODE = ZFIFSCM_REAS_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
ACTION_ID = ZFIFSCM_REAS_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFIFSCM_REAS_AC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFIFSCM_REAS_AC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFIFSCM_REAS_AC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFIFSCM_REAS_AC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_REAS_ACT WHERE
  CASE_TYPE = ZVFIFSCM_REAS_AC-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_REAS_AC-REASON_CODE AND
  ACTION_ID = ZVFIFSCM_REAS_AC-ACTION_ID .
    IF SY-SUBRC = 0.
    DELETE ZFIFSCM_REAS_ACT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFIFSCM_REAS_ACT WHERE
  CASE_TYPE = ZVFIFSCM_REAS_AC-CASE_TYPE AND
  REASON_CODE = ZVFIFSCM_REAS_AC-REASON_CODE AND
  ACTION_ID = ZVFIFSCM_REAS_AC-ACTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFIFSCM_REAS_ACT.
    ENDIF.
ZFIFSCM_REAS_ACT-MANDT =
ZVFIFSCM_REAS_AC-MANDT .
ZFIFSCM_REAS_ACT-CASE_TYPE =
ZVFIFSCM_REAS_AC-CASE_TYPE .
ZFIFSCM_REAS_ACT-REASON_CODE =
ZVFIFSCM_REAS_AC-REASON_CODE .
ZFIFSCM_REAS_ACT-ACTION_ID =
ZVFIFSCM_REAS_AC-ACTION_ID .
    IF SY-SUBRC = 0.
    UPDATE ZFIFSCM_REAS_ACT ##WARN_OK.
    ELSE.
    INSERT ZFIFSCM_REAS_ACT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFIFSCM_REAS_AC-UPD_FLAG,
STATUS_ZVFIFSCM_REAS_AC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFIFSCM_REAS_AC.
  SELECT SINGLE * FROM ZFIFSCM_REAS_ACT WHERE
CASE_TYPE = ZVFIFSCM_REAS_AC-CASE_TYPE AND
REASON_CODE = ZVFIFSCM_REAS_AC-REASON_CODE AND
ACTION_ID = ZVFIFSCM_REAS_AC-ACTION_ID .
ZVFIFSCM_REAS_AC-MANDT =
ZFIFSCM_REAS_ACT-MANDT .
ZVFIFSCM_REAS_AC-CASE_TYPE =
ZFIFSCM_REAS_ACT-CASE_TYPE .
ZVFIFSCM_REAS_AC-REASON_CODE =
ZFIFSCM_REAS_ACT-REASON_CODE .
ZVFIFSCM_REAS_AC-ACTION_ID =
ZFIFSCM_REAS_ACT-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
REASON_CODE = ZFIFSCM_REAS_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_REAS_AC-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_REAS_AC-DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
ACTION_ID = ZFIFSCM_REAS_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_REAS_AC-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_REAS_AC-ACTION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFIFSCM_REAS_AC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFIFSCM_REAS_AC-CASE_TYPE TO
ZFIFSCM_REAS_ACT-CASE_TYPE .
MOVE ZVFIFSCM_REAS_AC-REASON_CODE TO
ZFIFSCM_REAS_ACT-REASON_CODE .
MOVE ZVFIFSCM_REAS_AC-ACTION_ID TO
ZFIFSCM_REAS_ACT-ACTION_ID .
MOVE ZVFIFSCM_REAS_AC-MANDT TO
ZFIFSCM_REAS_ACT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFIFSCM_REAS_ACT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFIFSCM_REAS_ACT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFIFSCM_REAS_ACT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFIFSCM_REAS_AC USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFIFSCM_REAS_ACT-MANDT =
ZVFIFSCM_REAS_AC-MANDT .
ZFIFSCM_REAS_ACT-CASE_TYPE =
ZVFIFSCM_REAS_AC-CASE_TYPE .
ZFIFSCM_REAS_ACT-REASON_CODE =
ZVFIFSCM_REAS_AC-REASON_CODE .
ZFIFSCM_REAS_ACT-ACTION_ID =
ZVFIFSCM_REAS_AC-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
REASON_CODE = ZFIFSCM_REAS_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_REAS_AC-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_REAS_AC-DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZFIFSCM_ACTION WHERE
CASE_TYPE = ZFIFSCM_REAS_ACT-CASE_TYPE AND
ACTION_ID = ZFIFSCM_REAS_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFIFSCM_ACTIONT WHERE
CASE_TYPE = ZFIFSCM_ACTION-CASE_TYPE AND
ACTION_ID = ZFIFSCM_ACTION-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFIFSCM_REAS_AC-ACTION_TEXT =
ZFIFSCM_ACTIONT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFIFSCM_REAS_AC-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFIFSCM_REAS_AC-ACTION_TEXT .
    ENDIF.
ENDFORM.
