*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 24.09.2019 at 09:34:58
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFSCM_DM_CAT_RE................................*
FORM GET_DATA_ZVFSCM_DM_CAT_RE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFSCM_DM_CAT_REA WHERE
(VIM_WHERETAB) .
    CLEAR ZVFSCM_DM_CAT_RE .
ZVFSCM_DM_CAT_RE-MANDT =
ZFSCM_DM_CAT_REA-MANDT .
ZVFSCM_DM_CAT_RE-CASE_TYPE =
ZFSCM_DM_CAT_REA-CASE_TYPE .
ZVFSCM_DM_CAT_RE-CATEGORY =
ZFSCM_DM_CAT_REA-CATEGORY .
ZVFSCM_DM_CAT_RE-REASON_CODE =
ZFSCM_DM_CAT_REA-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
CATEGORY = ZFSCM_DM_CAT_REA-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_CAT_REA-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFSCM_DM_CAT_RE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFSCM_DM_CAT_RE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFSCM_DM_CAT_RE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFSCM_DM_CAT_RE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_CAT_REA WHERE
  CASE_TYPE = ZVFSCM_DM_CAT_RE-CASE_TYPE AND
  CATEGORY = ZVFSCM_DM_CAT_RE-CATEGORY AND
  REASON_CODE = ZVFSCM_DM_CAT_RE-REASON_CODE .
    IF SY-SUBRC = 0.
    DELETE ZFSCM_DM_CAT_REA .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_CAT_REA WHERE
  CASE_TYPE = ZVFSCM_DM_CAT_RE-CASE_TYPE AND
  CATEGORY = ZVFSCM_DM_CAT_RE-CATEGORY AND
  REASON_CODE = ZVFSCM_DM_CAT_RE-REASON_CODE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFSCM_DM_CAT_REA.
    ENDIF.
ZFSCM_DM_CAT_REA-MANDT =
ZVFSCM_DM_CAT_RE-MANDT .
ZFSCM_DM_CAT_REA-CASE_TYPE =
ZVFSCM_DM_CAT_RE-CASE_TYPE .
ZFSCM_DM_CAT_REA-CATEGORY =
ZVFSCM_DM_CAT_RE-CATEGORY .
ZFSCM_DM_CAT_REA-REASON_CODE =
ZVFSCM_DM_CAT_RE-REASON_CODE .
    IF SY-SUBRC = 0.
    UPDATE ZFSCM_DM_CAT_REA ##WARN_OK.
    ELSE.
    INSERT ZFSCM_DM_CAT_REA .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFSCM_DM_CAT_RE-UPD_FLAG,
STATUS_ZVFSCM_DM_CAT_RE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFSCM_DM_CAT_RE.
  SELECT SINGLE * FROM ZFSCM_DM_CAT_REA WHERE
CASE_TYPE = ZVFSCM_DM_CAT_RE-CASE_TYPE AND
CATEGORY = ZVFSCM_DM_CAT_RE-CATEGORY AND
REASON_CODE = ZVFSCM_DM_CAT_RE-REASON_CODE .
ZVFSCM_DM_CAT_RE-MANDT =
ZFSCM_DM_CAT_REA-MANDT .
ZVFSCM_DM_CAT_RE-CASE_TYPE =
ZFSCM_DM_CAT_REA-CASE_TYPE .
ZVFSCM_DM_CAT_RE-CATEGORY =
ZFSCM_DM_CAT_REA-CATEGORY .
ZVFSCM_DM_CAT_RE-REASON_CODE =
ZFSCM_DM_CAT_REA-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
CATEGORY = ZFSCM_DM_CAT_REA-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_CAT_REA-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_CAT_RE-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_CAT_RE-DESCRIPTION .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFSCM_DM_CAT_RE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFSCM_DM_CAT_RE-CASE_TYPE TO
ZFSCM_DM_CAT_REA-CASE_TYPE .
MOVE ZVFSCM_DM_CAT_RE-CATEGORY TO
ZFSCM_DM_CAT_REA-CATEGORY .
MOVE ZVFSCM_DM_CAT_RE-REASON_CODE TO
ZFSCM_DM_CAT_REA-REASON_CODE .
MOVE ZVFSCM_DM_CAT_RE-MANDT TO
ZFSCM_DM_CAT_REA-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFSCM_DM_CAT_REA'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFSCM_DM_CAT_REA TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFSCM_DM_CAT_REA'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFSCM_DM_CAT_RE USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFSCM_DM_CAT_REA-MANDT =
ZVFSCM_DM_CAT_RE-MANDT .
ZFSCM_DM_CAT_REA-CASE_TYPE =
ZVFSCM_DM_CAT_RE-CASE_TYPE .
ZFSCM_DM_CAT_REA-CATEGORY =
ZVFSCM_DM_CAT_RE-CATEGORY .
ZFSCM_DM_CAT_REA-REASON_CODE =
ZVFSCM_DM_CAT_RE-REASON_CODE .
    SELECT SINGLE * FROM SCMGATTR_CATEGO WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
CATEGORY = ZFSCM_DM_CAT_REA-CATEGORY .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_CATEGOT WHERE
CASE_TYPE = SCMGATTR_CATEGO-CASE_TYPE AND
CATEGORY = SCMGATTR_CATEGO-CATEGORY AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION =
SCMGATTR_CATEGOT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_CAT_RE-CAT_DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_CAT_REA-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_CAT_REA-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_CAT_RE-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_CAT_RE-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_CAT_RE-DESCRIPTION .
    ENDIF.
ENDFORM.
