*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 24.09.2019 at 09:54:09
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFSCM_DM_REA_AC................................*
FORM GET_DATA_ZVFSCM_DM_REA_AC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFSCM_DM_REA_ACT WHERE
(VIM_WHERETAB) .
    CLEAR ZVFSCM_DM_REA_AC .
ZVFSCM_DM_REA_AC-MANDT =
ZFSCM_DM_REA_ACT-MANDT .
ZVFSCM_DM_REA_AC-CASE_TYPE =
ZFSCM_DM_REA_ACT-CASE_TYPE .
ZVFSCM_DM_REA_AC-REASON_CODE =
ZFSCM_DM_REA_ACT-REASON_CODE .
ZVFSCM_DM_REA_AC-ACTION_ID =
ZFSCM_DM_REA_ACT-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_REA_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT SINGLE * FROM ZFSCM_DM_ACT WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_REA_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFSCM_DM_ACTT WHERE
CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-ACTION_TEXT =
ZFSCM_DM_ACTT-ACTION_TEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFSCM_DM_REA_AC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFSCM_DM_REA_AC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFSCM_DM_REA_AC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFSCM_DM_REA_AC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_REA_ACT WHERE
  CASE_TYPE = ZVFSCM_DM_REA_AC-CASE_TYPE AND
  REASON_CODE = ZVFSCM_DM_REA_AC-REASON_CODE AND
  ACTION_ID = ZVFSCM_DM_REA_AC-ACTION_ID .
    IF SY-SUBRC = 0.
    DELETE ZFSCM_DM_REA_ACT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_REA_ACT WHERE
  CASE_TYPE = ZVFSCM_DM_REA_AC-CASE_TYPE AND
  REASON_CODE = ZVFSCM_DM_REA_AC-REASON_CODE AND
  ACTION_ID = ZVFSCM_DM_REA_AC-ACTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFSCM_DM_REA_ACT.
    ENDIF.
ZFSCM_DM_REA_ACT-MANDT =
ZVFSCM_DM_REA_AC-MANDT .
ZFSCM_DM_REA_ACT-CASE_TYPE =
ZVFSCM_DM_REA_AC-CASE_TYPE .
ZFSCM_DM_REA_ACT-REASON_CODE =
ZVFSCM_DM_REA_AC-REASON_CODE .
ZFSCM_DM_REA_ACT-ACTION_ID =
ZVFSCM_DM_REA_AC-ACTION_ID .
    IF SY-SUBRC = 0.
    UPDATE ZFSCM_DM_REA_ACT ##WARN_OK.
    ELSE.
    INSERT ZFSCM_DM_REA_ACT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFSCM_DM_REA_AC-UPD_FLAG,
STATUS_ZVFSCM_DM_REA_AC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFSCM_DM_REA_AC.
  SELECT SINGLE * FROM ZFSCM_DM_REA_ACT WHERE
CASE_TYPE = ZVFSCM_DM_REA_AC-CASE_TYPE AND
REASON_CODE = ZVFSCM_DM_REA_AC-REASON_CODE AND
ACTION_ID = ZVFSCM_DM_REA_AC-ACTION_ID .
ZVFSCM_DM_REA_AC-MANDT =
ZFSCM_DM_REA_ACT-MANDT .
ZVFSCM_DM_REA_AC-CASE_TYPE =
ZFSCM_DM_REA_ACT-CASE_TYPE .
ZVFSCM_DM_REA_AC-REASON_CODE =
ZFSCM_DM_REA_ACT-REASON_CODE .
ZVFSCM_DM_REA_AC-ACTION_ID =
ZFSCM_DM_REA_ACT-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_REA_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_REA_AC-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_REA_AC-DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZFSCM_DM_ACT WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_REA_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFSCM_DM_ACTT WHERE
CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-ACTION_TEXT =
ZFSCM_DM_ACTT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_REA_AC-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_REA_AC-ACTION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFSCM_DM_REA_AC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFSCM_DM_REA_AC-CASE_TYPE TO
ZFSCM_DM_REA_ACT-CASE_TYPE .
MOVE ZVFSCM_DM_REA_AC-REASON_CODE TO
ZFSCM_DM_REA_ACT-REASON_CODE .
MOVE ZVFSCM_DM_REA_AC-ACTION_ID TO
ZFSCM_DM_REA_ACT-ACTION_ID .
MOVE ZVFSCM_DM_REA_AC-MANDT TO
ZFSCM_DM_REA_ACT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFSCM_DM_REA_ACT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFSCM_DM_REA_ACT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFSCM_DM_REA_ACT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFSCM_DM_REA_AC USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFSCM_DM_REA_ACT-MANDT =
ZVFSCM_DM_REA_AC-MANDT .
ZFSCM_DM_REA_ACT-CASE_TYPE =
ZVFSCM_DM_REA_AC-CASE_TYPE .
ZFSCM_DM_REA_ACT-REASON_CODE =
ZVFSCM_DM_REA_AC-REASON_CODE .
ZFSCM_DM_REA_ACT-ACTION_ID =
ZVFSCM_DM_REA_AC-ACTION_ID .
    SELECT SINGLE * FROM SCMGATTR_REASON WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
REASON_CODE = ZFSCM_DM_REA_ACT-REASON_CODE .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM SCMGATTR_REASONT WHERE
CASE_TYPE = SCMGATTR_REASON-CASE_TYPE AND
REASON_CODE = SCMGATTR_REASON-REASON_CODE AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-DESCRIPTION =
SCMGATTR_REASONT-DESCRIPTION .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_REA_AC-DESCRIPTION .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_REA_AC-DESCRIPTION .
    ENDIF.
    SELECT SINGLE * FROM SCMGCASETYPE WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZFSCM_DM_ACT WHERE
CASE_TYPE = ZFSCM_DM_REA_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_REA_ACT-ACTION_ID .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM ZFSCM_DM_ACTT WHERE
CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
LANGU = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZVFSCM_DM_REA_AC-ACTION_TEXT =
ZFSCM_DM_ACTT-ACTION_TEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFSCM_DM_REA_AC-ACTION_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_REA_AC-ACTION_TEXT .
    ENDIF.
ENDFORM.
