*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 24.09.2019 at 10:09:39
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVFSCM_DM_ACT...................................*
FORM GET_DATA_ZVFSCM_DM_ACT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFSCM_DM_ACT WHERE
(VIM_WHERETAB) .
    CLEAR ZVFSCM_DM_ACT .
ZVFSCM_DM_ACT-MANDT =
ZFSCM_DM_ACT-MANDT .
ZVFSCM_DM_ACT-CASE_TYPE =
ZFSCM_DM_ACT-CASE_TYPE .
ZVFSCM_DM_ACT-ACTION_ID =
ZFSCM_DM_ACT-ACTION_ID .
    SELECT SINGLE * FROM ZFSCM_DM_ACTT WHERE
CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFSCM_DM_ACT-ACTION_TEXT =
ZFSCM_DM_ACTT-ACTION_TEXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFSCM_DM_ACT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFSCM_DM_ACT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFSCM_DM_ACT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFSCM_DM_ACT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_ACT WHERE
  CASE_TYPE = ZVFSCM_DM_ACT-CASE_TYPE AND
  ACTION_ID = ZVFSCM_DM_ACT-ACTION_ID .
    IF SY-SUBRC = 0.
    DELETE ZFSCM_DM_ACT .
    ENDIF.
    DELETE FROM ZFSCM_DM_ACTT WHERE
    CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
    ACTION_ID = ZFSCM_DM_ACT-ACTION_ID .
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_ACT WHERE
  CASE_TYPE = ZVFSCM_DM_ACT-CASE_TYPE AND
  ACTION_ID = ZVFSCM_DM_ACT-ACTION_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFSCM_DM_ACT.
    ENDIF.
ZFSCM_DM_ACT-MANDT =
ZVFSCM_DM_ACT-MANDT .
ZFSCM_DM_ACT-CASE_TYPE =
ZVFSCM_DM_ACT-CASE_TYPE .
ZFSCM_DM_ACT-ACTION_ID =
ZVFSCM_DM_ACT-ACTION_ID .
    IF SY-SUBRC = 0.
    UPDATE ZFSCM_DM_ACT ##WARN_OK.
    ELSE.
    INSERT ZFSCM_DM_ACT .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM ZFSCM_DM_ACTT WHERE
    CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
    ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
    LANGU = SY-LANGU .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR ZFSCM_DM_ACTT.
ZFSCM_DM_ACTT-CASE_TYPE =
ZFSCM_DM_ACT-CASE_TYPE .
ZFSCM_DM_ACTT-ACTION_ID =
ZFSCM_DM_ACT-ACTION_ID .
ZFSCM_DM_ACTT-LANGU =
SY-LANGU .
      ENDIF.
ZFSCM_DM_ACTT-ACTION_TEXT =
ZVFSCM_DM_ACT-ACTION_TEXT .
    IF SY-SUBRC = 0.
    UPDATE ZFSCM_DM_ACTT ##WARN_OK.
    ELSE.
    INSERT ZFSCM_DM_ACTT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFSCM_DM_ACT-UPD_FLAG,
STATUS_ZVFSCM_DM_ACT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFSCM_DM_ACT.
  SELECT SINGLE * FROM ZFSCM_DM_ACT WHERE
CASE_TYPE = ZVFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZVFSCM_DM_ACT-ACTION_ID .
ZVFSCM_DM_ACT-MANDT =
ZFSCM_DM_ACT-MANDT .
ZVFSCM_DM_ACT-CASE_TYPE =
ZFSCM_DM_ACT-CASE_TYPE .
ZVFSCM_DM_ACT-ACTION_ID =
ZFSCM_DM_ACT-ACTION_ID .
    SELECT SINGLE * FROM ZFSCM_DM_ACTT WHERE
CASE_TYPE = ZFSCM_DM_ACT-CASE_TYPE AND
ACTION_ID = ZFSCM_DM_ACT-ACTION_ID AND
LANGU = SY-LANGU .
    IF SY-SUBRC EQ 0.
ZVFSCM_DM_ACT-ACTION_TEXT =
ZFSCM_DM_ACTT-ACTION_TEXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFSCM_DM_ACT-ACTION_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFSCM_DM_ACT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFSCM_DM_ACT-CASE_TYPE TO
ZFSCM_DM_ACT-CASE_TYPE .
MOVE ZVFSCM_DM_ACT-ACTION_ID TO
ZFSCM_DM_ACT-ACTION_ID .
MOVE ZVFSCM_DM_ACT-MANDT TO
ZFSCM_DM_ACT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFSCM_DM_ACT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFSCM_DM_ACT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFSCM_DM_ACT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE ZFSCM_DM_ACT-CASE_TYPE TO
ZFSCM_DM_ACTT-CASE_TYPE .
MOVE ZFSCM_DM_ACT-ACTION_ID TO
ZFSCM_DM_ACTT-ACTION_ID .
MOVE SY-LANGU TO
ZFSCM_DM_ACTT-LANGU .
MOVE ZVFSCM_DM_ACT-MANDT TO
ZFSCM_DM_ACTT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFSCM_DM_ACTT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFSCM_DM_ACTT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFSCM_DM_ACTT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
